// Globe variables
const AriesSentences = [
  "The stars reveal a bold new opportunity coming your way next month - be ready to take the first step.",
  "Your fiery energy will attract an important figure into your life very soon - this connection will change everything.",
  "Unexpected financial gains are predicted when Mars aligns with your sign in the coming weeks.",
  "A secret admirer has been hesitant to approach you - their reveal will surprise you.",
  "The universe is preparing to reward your recent efforts in a way you can't yet imagine.",
  "An old dream you abandoned will resurface with new possibilities before the season ends.",
  "Someone from your past will return with information that answers long-held questions.",
  "Your natural leadership will be recognized in an unexpected setting soon - prepare to step up.",
  "Travel plans that seem uncertain now will fall into place miraculously when you least expect it.",
  "The next full moon brings a revelation about your true purpose - pay attention to dreams.",
  "A risk you've been afraid to take will prove to be your greatest opportunity this year.",
  "Your creativity will reach new heights - an innovative idea will bring recognition.",
  "Someone close has been hiding their true feelings - the truth will emerge under emotional circumstances.",
  "Financial obstacles will suddenly clear when Jupiter influences your sector of abundance.",
  "A chance encounter in an ordinary place will lead to an extraordinary connection.",
  "Your competitive spirit will be tested soon - stay true to your values and you'll prevail.",
  "An investment you made (time, money or emotion) will yield surprising returns.",
  "Health improvements you've sought are coming - the stars indicate a positive shift.",
  "A professional opportunity you thought was lost will reappear in a better form.",
  "Your words will have powerful impact soon - choose them carefully as they may change a relationship forever.",
  "The solution to a persistent problem will come from an unexpected source - stay open.",
  "Your personal magnetism is especially strong now - use it to manifest what you desire.",
  "A family matter will resolve in your favor, bringing peace you've longed for.",
  "Someone you trust will surprise you with their loyalty during a difficult moment.",
  "The universe has been aligning circumstances to deliver a wish you made long ago - prepare to receive."
];

const TaurusSentences = [
  "Financial stability you've worked for is coming - an unexpected source will contribute to your security.",
  "Your patience will be rewarded when Venus blesses your sign with a long-awaited breakthrough.",
  "A creative project you've nurtured will soon attract attention from influential people.",
  "Love is written in your stars - someone appreciates your steadfast nature more than you know.",
  "An inheritance or gift will come your way, bringing both resources and emotional significance.",
  "Your practical skills will be recognized in a professional setting - don't downplay your abilities.",
  "A home-related decision you've been weighing will prove to be the right choice in hindsight.",
  "Someone from your past will reappear with an offer that deserves serious consideration.",
  "Your senses will guide you to an important discovery - trust your intuition this month.",
  "A health concern will improve dramatically when you implement a natural solution.",
  "Financial advice you receive unexpectedly will lead to greater prosperity - verify but stay open.",
  "Your stubbornness will serve you well in an upcoming challenge - stand your ground.",
  "A secret admirer appreciates your sensual nature - they'll make their interest known subtly.",
  "An investment in land or property will prove wiser than you anticipated.",
  "Your appreciation for beauty will lead you to a discovery that enhances your daily life.",
  "A relationship will deepen through shared sensory experiences - plan something special.",
  "Your determination will overcome an obstacle that seemed immovable - victory is coming.",
  "A family matter requiring your practical approach will resolve successfully.",
  "Your taste and discernment will be recognized - someone seeks your opinion on an important matter.",
  "Money you thought was lost will return to you in an unexpected way.",
  "A workplace change you resisted will ultimately create better conditions for you.",
  "Your capacity for pleasure will expand - prepare for new experiences that delight your senses.",
  "A long-held dream will manifest when you least expect it - the timing will be perfect.",
  "Your loyalty will be tested, but staying true to your values will bring rewards.",
  "The earth element strengthens you now - grounding practices will enhance your natural gifts."
];

const GeminiSentences = [
  "Your quick mind will solve a problem that's stumped others - recognition is coming.",
  "A conversation you have this week will open doors you didn't know existed - speak freely.",
  "Your adaptability will be your greatest asset as unexpected changes bring new opportunities.",
  "A message you've been waiting for will arrive at just the right moment - stay alert.",
  "Networking will prove especially fruitful - someone you meet casually has important connections.",
  "Your curiosity will lead you to knowledge that gives you a competitive edge.",
  "A short trip will have long-lasting effects on your personal growth - say yes to invitations.",
  "Creative ideas are flowing - capture them all, as one will be more valuable than you realize.",
  "Someone has been misrepresenting facts - the truth will emerge to your benefit.",
  "Your social circle is about to expand in exciting ways - new friends will broaden your horizons.",
  "A skill you consider ordinary is actually your hidden ticket to success - develop it further.",
  "Financial news coming soon will require quick thinking - trust your instincts.",
  "A sibling or neighbor will share information that changes your perspective on an important matter.",
  "Your ability to see both sides will help mediate a conflict - your role will be appreciated.",
  "Technology will play an unexpected role in solving a persistent problem in your life.",
  "A book or course you encounter will provide exactly the guidance you need now.",
  "Your words will have power - a speech or written communication will influence more than you expect.",
  "Someone from your past will reconnect with an offer or idea worth considering.",
  "A transportation delay will work in your favor - what seems inconvenient will bring benefit.",
  "Your mental agility will help you navigate complex emotional waters successfully.",
  "A contract or agreement will need careful review - overlooked details matter greatly.",
  "Your natural charm will open doors in a professional setting - use it wisely.",
  "An idea you share casually will inspire someone who can help make it reality.",
  "Communication devices will play a surprising role in a romantic development.",
  "The universe is preparing to answer a question you've been asking - the response will come through conversation."
];

const CancerSentences = [
  "Your emotional intelligence will guide you through a difficult situation successfully.",
  "Family matters will take a positive turn - your nurturing approach makes all the difference.",
  "A home improvement will increase both comfort and value - trust your instincts about this.",
  "Your intuition is especially strong now - pay attention to dreams and gut feelings.",
  "Financial security grows when you listen to conservative advice - resist impulsive spending.",
  "Someone from your past will reappear with healing words you've needed to hear.",
  "Your creative talents are blossoming - share them despite any insecurities.",
  "A property or housing opportunity will emerge that feels destined - act quickly when it appears.",
  "Your ability to read between the lines will uncover important hidden information.",
  "Emotional healing will come through an unexpected source - be open to receiving comfort.",
  "Family traditions will take on new meaning and bring unexpected joy this season.",
  "Your sensitivity is a strength - it will help you navigate a professional challenge skillfully.",
  "A parent or mentor figure has guidance you need to hear - be receptive this week.",
  "Nostalgia will lead you to rediscover something valuable you'd forgotten.",
  "Your caring nature will be recognized and appreciated in a meaningful way.",
  "A water-related environment will be the setting for an important insight or meeting.",
  "Financial intuition will guide you to make a wise decision - trust your first instinct.",
  "Someone younger will teach you an important lesson about joy and simplicity.",
  "Home cooking or hosting will create bonds that lead to future opportunities.",
  "A childhood dream will resurface with new possibilities for fulfillment.",
  "Your emotional boundaries are being strengthened - this protects you from energy drains.",
  "A family secret will come to light, bringing understanding and closure.",
  "Your connection to the moon's cycles will enhance your timing for important decisions.",
  "Comfort foods will take on healing properties during an emotional time coming soon.",
  "The universe is preparing to answer an emotional prayer - have faith in divine timing."
];

const LeoSentences = [
  "Your natural charisma is at a peak - use this time to make important connections.",
  "A creative project will receive unexpected recognition - prepare for compliments.",
  "Leadership opportunities are coming - your confidence will inspire others to follow.",
  "Financial gains are likely when you showcase your unique talents - don't hold back.",
  "Romantic attention will surprise you - someone admires your vibrant energy.",
  "A risk you take for love or creativity will pay off beautifully - trust your heart.",
  "Your dramatic flair will help resolve a conflict in your favor - use it wisely.",
  "Children or younger people in your life will bring an important message.",
  "A performance or presentation will have greater impact than you anticipate.",
  "Generosity will be returned to you multiplied - give freely when inspired.",
  "Your pride may be tested, but humility will win you greater respect.",
  "A bold move in your career will position you for future success - the timing is right.",
  "Someone has been observing your strength and will seek your guidance soon.",
  "A financial opportunity tied to entertainment or luxury goods will arise.",
  "Your health and vitality will improve when you prioritize joy in your routine.",
  "A romantic gesture will have lasting effects - express your feelings boldly.",
  "Your ability to command attention will help you negotiate favorable terms.",
  "A long-held dream will begin to manifest in unexpected ways - stay alert.",
  "Someone important notices your leadership - prepare for an exciting offer.",
  "Creative blocks will dissolve when you reconnect with your childlike wonder.",
  "A gamble on yourself will prove worthwhile - believe in your special gifts.",
  "Your dramatic instincts will help you navigate a social situation perfectly.",
  "A secret admirer is drawn to your radiant energy - they'll make contact soon.",
  "Generosity you showed in the past will return to you in a meaningful way.",
  "The universe is aligning to spotlight your talents - prepare to shine brighter than ever."
];

const VirgoSentenses = [
  "Your attention to detail will uncover an important opportunity others have missed.",
  "Health improvements are coming when you implement a careful, systematic approach.",
  "A service you provide will be recognized and rewarded beyond expectations.",
  "Financial organization will lead to discoveries of resources you didn't know you had.",
  "Your analytical skills will solve a problem that's baffled others - credit will come.",
  "A pet or small animal will play an unexpected role in an important moment.",
  "Someone values your practical advice more than you realize - they'll soon express gratitude.",
  "A work-related challenge will showcase your problem-solving abilities impressively.",
  "Daily routines will lead to encounters that blossom into valuable connections.",
  "Your humility will be recognized as a strength when others boast foolishly.",
  "A dietary change will have positive effects on both physical and mental clarity.",
  "Someone needs your organizational skills - helping them will benefit you too.",
  "A mistake you catch and correct will prevent larger problems - trust your perfectionism.",
  "Financial paperwork will reveal an error in your favor - review documents carefully.",
  "Your quiet competence will be noticed by someone who can advance your goals.",
  "A healing practice or health regimen will prove especially effective now.",
  "Criticism you received will soon be proven wrong - your way was correct after all.",
  "A tool or technology you acquire will increase your productivity dramatically.",
  "Your ability to simplify complexity will make you invaluable in an upcoming project.",
  "Nature will provide solace and answers during a period of confusion.",
  "A small, thoughtful gesture will have greater impact than grand displays.",
  "Your practical skills will be the foundation for an exciting new opportunity.",
  "Someone's casual remark will contain the solution to a problem you've pondered.",
  "A habit you've worked to develop will soon yield visible benefits - persist.",
  "The universe is organizing details in your favor - trust the process unfolding."
];

const LibraSentences = [
  "Your sense of balance will help resolve a conflict that's troubled others.",
  "Partnership opportunities are blossoming - someone seeks your collaboration.",
  "A legal or contractual matter will resolve in your favor through fair compromise.",
  "Your eye for beauty will lead you to a discovery that enhances your environment.",
  "Social connections will prove valuable in unexpected ways - attend gatherings.",
  "Someone admires your grace under pressure - this observation will benefit you.",
  "A creative partnership will flourish when you balance giving and receiving.",
  "Financial fairness will be restored after a period of imbalance - justice comes.",
  "Your diplomatic skills will be needed to navigate a delicate situation successfully.",
  "Love is in the air - someone appreciates your harmony and seeks to get closer.",
  "An artistic endeavor will bring satisfaction and possibly unexpected profit.",
  "Your ability to see all sides makes you the perfect mediator - your time to shine comes.",
  "A home decoration or improvement will bring more joy than you anticipate.",
  "Someone from your past will reappear with an apology or explanation you've needed.",
  "Your sense of style will attract compliments and possibly romantic attention.",
  "A decision you've weighed carefully will prove to be exactly right in hindsight.",
  "Balance between work and personal life will lead to greater overall happiness.",
  "Fair treatment you advocated for others will return to benefit you directly.",
  "A relationship at a crossroads will find new harmony through open communication.",
  "Your refined tastes will guide you to a valuable acquisition or experience.",
  "Someone needs your objective advice - providing it will strengthen your bond.",
  "A legal document deserves careful review - your scrutiny will prevent future issues.",
  "Social media connections will lead to an unexpected opportunity - engage actively.",
  "Your charm will smooth over a difficult situation that could have turned negative.",
  "The universe is restoring balance to an area of imbalance in your life - have faith."
];

const ScorpioSentences = [
  "Your intensity will attract a powerful opportunity - don't hold back your passion.",
  "A financial transformation is beginning - trust your instincts about investments.",
  "Secrets will come to light that give you an advantage in an important matter.",
  "Your magnetic presence will draw someone important into your orbit soon.",
  "Research you conduct will uncover valuable information others have missed.",
  "A relationship will deepen in ways that surprise and fulfill you emotionally.",
  "Your ability to perceive truth will help you avoid a potentially costly mistake.",
  "Hidden resources will become available to you when you need them most.",
  "A professional situation that seemed stagnant will suddenly shift in your favor.",
  "Someone's loyalty will be tested, and they'll prove worthy of your trust.",
  "Emotional healing will occur through an intense but necessary confrontation.",
  "Your intuition is especially sharp now - pay attention to dreams and gut feelings.",
  "A financial sacrifice you made will be returned to you multiplied.",
  "Power dynamics in a relationship will balance out, bringing greater harmony.",
  "Your investigative skills will solve a mystery that's puzzled those around you.",
  "A health concern will improve dramatically when you address the root cause.",
  "Someone has been observing your strength and will seek your guidance soon.",
  "Taboo or difficult topics will become easier to discuss, leading to breakthroughs.",
  "Your sexual magnetism is particularly strong now - use this energy wisely.",
  "A legal or inheritance matter will resolve in your favor after patience.",
  "Your capacity for rebirth will help you transform an area of limitation into strength.",
  "Someone from your past will reappear with information that changes everything.",
  "Psychological insights will lead to personal liberation from old patterns.",
  "A financial windfall is possible when you least expect it - stay prepared.",
  "The universe is aligning to bring you profound transformation - embrace the change."
];

const SagittariusSentences = [
  "Your adventurous spirit will lead you to an exciting opportunity abroad or through education.",
  "A legal or travel-related matter will resolve favorably - have faith.",
  "Your optimism will inspire someone important to take a chance on you.",
  "Publishing or broadcasting your ideas will bring unexpected rewards.",
  "A chance meeting with a foreigner or scholar will expand your horizons.",
  "Your honesty will be appreciated in a situation where others are being deceptive.",
  "Higher education or spiritual pursuits will open doors you didn't know existed.",
  "A risk you take for adventure or growth will pay off beautifully.",
  "Your sense of humor will diffuse a tense situation to your advantage.",
  "Travel plans that seem uncertain now will work out better than you imagined.",
  "Someone will seek your philosophical perspective on an important matter.",
  "A bold move in your career will position you for exciting future opportunities.",
  "Your athletic abilities or love of nature will lead to an important connection.",
  "Financial gains are possible through international connections or imports/exports.",
  "A book or course will provide exactly the guidance you need at this time.",
  "Your faith will be rewarded when a seemingly hopeless situation turns around.",
  "Someone admires your free spirit and will soon make their feelings known.",
  "A legal matter will conclude in your favor after a period of uncertainty.",
  "Your ability to see the big picture will help you make an important decision correctly.",
  "A long-distance connection will become more significant than you anticipated.",
  "Your idealism will inspire others when you least expect to have an audience.",
  "A teaching or mentoring opportunity will arise that fulfills you deeply.",
  "Spiritual growth will accelerate, bringing clarity to long-held questions.",
  "An adventure you plan will have lasting positive effects on your perspective.",
  "The universe is expanding your horizons - prepare for exciting new possibilities."
];

const CapricornSentences = [
  "Your disciplined approach will lead to recognition from important figures soon.",
  "Career advancements are coming - your patience and hard work are about to pay off.",
  "A financial plan you implemented will prove wiser than you anticipated.",
  "Your practical advice will be sought by someone who previously doubted you.",
  "Authority figures will notice your reliability - prepare for increased responsibilities.",
  "An investment in property or long-term assets will prove especially shrewd.",
  "Your perseverance through difficult times will soon be rewarded publicly.",
  "Family obligations will lead to unexpected opportunities - embrace them.",
  "Traditional methods will serve you better than new trends in an upcoming decision.",
  "Financial stability you've worked for will soon provide new freedoms.",
  "Someone older has guidance you need to hear - be receptive in coming weeks.",
  "Your reputation for integrity will open doors that remain closed to others.",
  "A goal you set long ago will finally be within reach - persist a little longer.",
  "Business partnerships formed now will have lasting, profitable results.",
  "Your ability to endure will be tested, but the outcome will justify the struggle.",
  "Practical skills you consider ordinary are actually your ticket to success.",
  "A structured approach to health will yield better results than quick fixes.",
  "Delayed gratification will prove worthwhile when you see the final results.",
  "Someone notices your quiet competence and will offer an important opportunity.",
  "Financial caution will protect you from losses others will experience.",
  "Traditional values will serve you well in an upcoming moral dilemma.",
  "A mentor will provide guidance that helps you avoid a costly mistake.",
  "Your responsible nature will be rewarded in an unexpected, meaningful way.",
  "Long-term planning will put you ahead of competitors - continue being methodical.",
  "The universe is solidifying foundations for your future success - trust the process."
];

const AquariusSentences = [
  "Your innovative ideas will attract attention from influential people soon.",
  "A friend will prove to be more important to your future than you realize.",
  "Technology will play an unexpected role in solving a persistent problem.",
  "Your humanitarian instincts will lead you to an important cause or community.",
  "Sudden insights will provide solutions to problems that have puzzled others.",
  "Group activities will lead to connections that advance your personal goals.",
  "Your uniqueness will be appreciated by someone who values originality.",
  "An invention or creative solution will gain recognition in unexpected ways.",
  "Financial gains are possible through collaborative or unconventional means.",
  "Your social circle is about to expand in exciting, unpredictable directions.",
  "A scientific or technological development will personally benefit you.",
  "Someone from your past will reconnect with information that helps your future.",
  "Your ability to think outside the box will save a project from failure.",
  "Friends will provide support exactly when you need it most - don't hesitate to ask.",
  "A sudden change in plans will actually work to your advantage - stay flexible.",
  "Your vision for the future will inspire others to join your cause or project.",
  "Unconventional relationships will prove more meaningful than traditional ones.",
  "A gadget or technology you acquire will significantly improve your daily life.",
  "Your social media presence will attract opportunities - engage authentically.",
  "Someone needs your objective advice - your perspective will help them greatly.",
  "A friendship will deepen in ways that surprise and fulfill you emotionally.",
  "Your progressive ideas will find receptive audiences when you least expect it.",
  "Teamwork will lead to results that surpass what you could achieve alone.",
  "A sudden realization will change your perspective on an important matter.",
  "The universe is orchestrating synchronicities to advance your unique path - pay attention."
];

const PiscesSentences = [
  "Your compassion will lead you to someone who needs exactly what you can offer.",
  "Creative projects are blessed now - your imagination will produce something special.",
  "A spiritual connection or practice will provide guidance at a crucial moment.",
  "Your intuition is especially strong - pay attention to dreams and subtle signs.",
  "Healing energy surrounds you - both giving and receiving comfort will be powerful.",
  "Artistic talents you've undervalued will be recognized and appreciated.",
  "A water-related environment will be the setting for an important insight or meeting.",
  "Someone needs your empathy and understanding - your support will make a difference.",
  "Financial intuition will guide you to make a surprisingly wise decision.",
  "A sacrifice you made will be returned to you in unexpected, beautiful ways.",
  "Your ability to sense others' feelings will help avoid a potential conflict.",
  "Music or poetry will carry a special message for you in the coming weeks.",
  "A healthcare or healing profession could hold unexpected opportunities for you.",
  "Someone from your past will reappear with an apology or closure you've needed.",
  "Your gentle approach will succeed where forceful methods have failed.",
  "A synchronicity will confirm you're on the right path - pay attention to signs.",
  "Helping someone less fortunate will bring you unexpected blessings.",
  "Your dreams contain important messages - keep a journal by your bedside.",
  "A creative idea dismissed as impractical will prove to have real value.",
  "Your faith will be rewarded when a seemingly hopeless situation improves.",
  "Spiritual or religious connections will provide comfort and guidance soon.",
  "Someone secretly admires your sensitive nature - they'll make their feelings known.",
  "A film, book, or artwork will speak to you profoundly at the right moment.",
  "Your imagination holds the key to solving a practical problem creatively.",
  "The universe is sending you love and healing - open your heart to receive it."
];

const messagesNumber = 25;

// Function to return a random index
const randSelector = () => Math.floor(Math.random()*messagesNumber);
